mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('polls.urls')),
    path('admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.urls import path
from . import views
app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/detail/', views.detail_list_question, name='details'),
    path('list/', views.question_list, name='question_list'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('<int:question_id>/votes/', views.total_vote, name='votes')

]

mysite/polls/models.py
from django.db import models
from django.db.models.query import QuerySet
import datetime

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    time_date = models.DateField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.time_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete= models.CASCADE)
    choice_text = models.CharField(max_length=200)
    vote = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

mysite/polls/views.py
from django.shortcuts import render
from django.http import HttpResponse, response
from .models import Question

# Create your views here.


def index(request):
    taisan = ['dien thoai', 'tui sach', 'may tinh', ]
    myname = 'Huynh Sang'
    context = {'name': myname, 'taisan': taisan}
    return render(request, "./polls/index.html", context)


def detail(request, question_id):
    return HttpResponse("Ban dang xem cau hoi thu: %s" % question_id)


def vote(request, question_id):
    return HttpResponse("Ban dang vote cau hoi thu %s" % question_id)


def question_list(request):
    list_question = Question.objects.all()
    context = {'list': list_question}
    return render(request, "./polls/question_list.html", context)


def detail_list_question(request, question_id):
    q = Question.objects.get(pk=question_id)
    return render(request, "./polls/detail_list_question.html", {"qs": q})


def total_vote(request, question_id):
    q = Question.objects.get(pk=question_id)
    try:
        data = request.POST['choice']
        c = q.choice_set.get(pk=data)
    except:
        HttpResponse('Khong co cau tra loi')
    c.vote = c.vote + 1
    c.save()
    return render(request,'./polls/total_vote.html',{'qs':q})

mysite/polls/templates/polls/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title %}{%endblock%}</title>
    <link rel="stylesheet" href="{% static '/polls/style.css'%}">

</head>

<body>
    <div class="header">
        <h1>My website</h1>
    </div>
    <div class="menu">
        <ul>
            <li>Link 1</li>
            <li>Link 2</li>
            <li>Link 3</li>
            <li>Link 4</li>
        </ul>
    </div>
    <div class="content">
        {%block content%}{%endblock%}
    </div>
</body>

</html>

mysite/polls/templates/polls/detail_list_question.html
{%extends "polls/base.html"%}
{%block title%}Detail{%endblock%}
{%block content%}
{{qs.question_text}}
    <form action="{%url 'polls:votes' qs.id %}" method="post">
        {% csrf_token %}
        <ul>
            {%for item in qs.choice_set.all%}
        <li><input type="radio" value="{{item.id}}" name="choice">{{item.choice_text}}</li>
        {%endfor%}
        <button type="submit" value="send">Gui</button>
        </ul>
    </form>

{%endblock%}

mysite/polls/templates/polls/index.html
{%extends "polls/base.html"%}
{%block title%}Home{%endblock%}
{%block content%}
<h1>Đây là templates</h1>
<p>Mình tên là <b>{{name}}</b></p>
<h2>Tai san cua toi gom:</h2>
<ul>
    {%for item in taisan%}
    <li>{{item}}</li>
    {%endfor%}
</ul>
{%endblock%}

mysite/polls/templates/polls/question_list.html
{%extends "polls/base.html"%}

{%block content%}
<ol>
    {%if list%}
    {%for item in list%}
    <a href="{%url 'polls:details' item.id %}"><p>{{item.question_text}}</p></a>
    {%endfor%}
    {%else%}
    <h3 style="color: red;">Khong co cau hoi !</h3>
    {%endif%}

</ol>
{%endblock%}

mysite/polls/templates/polls/total_vote.html
{%extends "polls/base.html"%}
{%block title%}Votes{%endblock%}
{%block content%}
        {%if qs%}
    {{qs.question_text}}
    <p>Ket qua cuoc binh chon: </p>
    {%for item in qs.choice_set.all%}
        <p>{{item.choice_text}}: <span style="color: chartreuse;">{{item.vote}}</span></p>
    {%endfor%}
    <a href="{%url 'polls:question_list'%}">Back</a>
    {%endif%}
{%endblock%}